### ISSUE TITLE
rpc call to create a wallet?

### ISSUE THREAD

**Issue by thestick613** [dashpay/dash#3760] opened 2020-10-04 19:27 UTC
What is the RPC call to create a new wallet? Can a dash node manage multiple wallets?

**Comment by PastaPastaPasta** [comment] 2020-10-05 17:59
The PR that introduces `createwallet` rpc was bitcoin#13058. This is not included in Dash v0.16, however, likely will be included in v0.17

**Comment by thestick613** [comment] 2020-10-05 18:50
It seems dash core can't handle multiple wallets easily enough ... yet.

**Comment by PastaPastaPasta** [comment] 2020-10-11 18:53
This is a duplicate of https://github.com/dashpay/dash/issues/2657, so I'm gonna close this one. Feel free to open a new issue if you have any other problems (or comment on that issue)

**Closed by PastaPastaPasta** 2020-10-11 18:53 UTC
