### ISSUE TITLE
GUI: Masternode tab doesn't refresh on MN IP address change

### ISSUE THREAD

**Issue by Technologov** [dashpay/dash#1419] opened 2017-03-28 23:33 UTC
Hello,

In Dash Core GUI, Masternode Tab, Address sub-tab, after I changed my MN  IP address (masternode.conf), the GUI doesn't refresh and shows an old IP address.
My Masternodes were in 'MISSING' status, but the bug may follow other statuses also.

Restarting Dash Core doesn't solve the problem.

Version: Dash Core 12.1.4 on Windows 7 x64.

-Technologov, 29.03.2017.

**Comment by nmarley** [comment] 2018-04-27 00:45
Duplicate of #1338, closing

**Closed by nmarley** 2018-04-27 00:45 UTC
