### ISSUE TITLE
Unable to sync masternode list

### ISSUE THREAD

**Issue by rex4539** [dashpay/dash#2112] opened 2018-06-11 18:06 UTC
Steps:
Launch latest client built locally from develop branch.

What happened:
Unable to sync masternode list.

```
2018-06-11 17:27:04 CMasternodeSync::SwitchToNextAsset -- Starting MASTERNODE_SYNC_WAITING
2018-06-11 17:27:04 ProcessNewBlock : ACCEPTED
2018-06-11 17:27:09 CMasternodeSync::ProcessTick -- nTick 259 nRequestedMasternodeAssets 1 nRequestedMasternodeAttempt 0 nSyncProgress 0.000000
2018-06-11 17:27:12 DSTX -- Got Masternode transaction 27e0861b1ec74a5fad7c74a0e29c7e8949ceef87a46af294b46964e0442bcbec
2018-06-11 17:27:12 PrioritiseTransaction: 27e0861b1ec74a5fad7c74a0e29c7e8949ceef87a46af294b46964e0442bcbec priority += 1000.000000, fee += 0.10
2018-06-11 17:27:12 DSTX -- Masternode transaction accepted, txid=27e0861b1ec74a5fad7c74a0e29c7e8949ceef87a46af294b46964e0442bcbec, peer=7
2018-06-11 17:27:14 ERROR: Error reading proxy response
2018-06-11 17:27:15 CMasternodeSync::ProcessTick -- nTick 265 nRequestedMasternodeAssets 1 nRequestedMasternodeAttempt 0 nSyncProgress 0.000000
2018-06-11 17:27:20 Socks5() connect to dnsseed.dashpay.io:9999 failed: host unreachable
2018-06-11 17:27:21 CMasternodeSync::ProcessTick -- nTick 271 nRequestedMasternodeAssets 1 nRequestedMasternodeAttempt 0 nSyncProgress 0.000000
2018-06-11 17:27:27 CMasternodeSync::ProcessTick -- nTick 277 nRequestedMasternodeAssets 1 nRequestedMasternodeAttempt 0 nSyncProgress 0.000000
2018-06-11 17:27:28 receive version message: /Dash Core:0.12.2.3/: version 70208, blocks=885297, us=93.115.95.202:60987, peer=8
2018-06-11 17:27:33 CMasternodeSync::ProcessTick -- nTick 283 nRequestedMasternodeAssets 1 nRequestedMasternodeAttempt 0 nSyncProgress 0.000000
2018-06-11 17:27:33 CMasternodeSync::ProcessTick -- nTick 283 nRequestedMasternodeAssets 1 -- requesting sporks from peer=8
2018-06-11 17:27:39 Socks5() connect to dnsseed.dashpay.io:9999 failed: host unreachable
2018-06-11 17:27:39 CMasternodeSync::ProcessTick -- nTick 289 nRequestedMasternodeAssets 1 nRequestedMasternodeAttempt 0 nSyncProgress 0.000000
2018-06-11 17:27:39 CMasternodeSync::SwitchToNextAsset -- Completed MASTERNODE_SYNC_WAITING in 35s
2018-06-11 17:27:39 CMasternodeSync::SwitchToNextAsset -- Starting MASTERNODE_SYNC_LIST
2018-06-11 17:27:44 CMasternodeMan::AskForMN -- Asking new peer 144.76.247.104:0 for missing masternode entry: 10c094626ca7d21879aecbe1e06effb6170710d54f0b7e692fb4e0f5ad5de9aa-1
2018-06-11 17:27:50 CMasternodeSync::ProcessTick -- nTick 295 nRequestedMasternodeAssets 2 nRequestedMasternodeAttempt 0 nSyncProgress 0.250000
2018-06-11 17:27:56 CMasternodeSync::ProcessTick -- nTick 301 nRequestedMasternodeAssets 2 nRequestedMasternodeAttempt 0 nSyncProgress 0.250000
2018-06-11 17:27:59 ERROR: Error reading proxy response
2018-06-11 17:28:01 Socks5() connect to dnsseed.dashpay.io:9999 failed: host unreachable
2018-06-11 17:28:02 receive version message: /Dash Core:0.12.2.3/: version 70208, blocks=885297, us=185.220.101.28:37827, peer=9
2018-06-11 17:28:02 CMasternodeSync::ProcessTick -- nTick 307 nRequestedMasternodeAssets 2 nRequestedMasternodeAttempt 0 nSyncProgress 0.250000
2018-06-11 17:28:02 CMasternodeSync::ProcessTick -- nTick 307 nRequestedMasternodeAssets 2 -- requesting sporks from peer=9
2018-06-11 17:28:05 Socks5() connect to dnsseed.dashpay.io:9999 failed: host unreachable
2018-06-11 17:28:06 receive version message: /Dash Core:0.12.2.3/: version 70208, blocks=885297, us=197.231.221.211:40526, peer=10
2018-06-11 17:28:08 Socks5() connect to dnsseed.dashpay.io:9999 failed: host unreachable
2018-06-11 17:28:08 CMasternodeSync::ProcessTick -- nTick 313 nRequestedMasternodeAssets 2 nRequestedMasternodeAttempt 0 nSyncProgress 0.250000
2018-06-11 17:28:08 CMasternodeSync::ProcessTick -- nTick 313 nRequestedMasternodeAssets 2 -- requesting sporks from peer=10
2018-06-11 17:28:09 ThreadSocketHandler -- removing node: peer=11 addr=188.166.25.114:9999 nRefCount=2 fInbound=0 fMasternode=0
2018-06-11 17:28:15 CMasternodeSync::ProcessTick -- nTick 319 nRequestedMasternodeAssets 2 nRequestedMasternodeAttempt 0 nSyncProgress 0.250000
2018-06-11 17:28:15 CMasternodeSync::ProcessTick -- nTick 319 nRequestedMasternodeAssets 2 -- timeout
2018-06-11 17:28:15 CMasternodeSync::ProcessTick -- ERROR: failed to sync MASTERNODE_SYNC_LIST
```

Expected result:
Masternode list syncs.

Notes:
This bug was introduced recently (last couple of weeks).

**Comment by thephez** [comment] 2018-06-11 18:16
Couple quick thoughts:
1. Does it work on testnet (looks like your are running it on mainnet)? I would try that first (if you have not already). 
2. Is your connection good?  I see some host unreachable messages in the log.
3. Is the issue consistent (if you do a `mnsync reset`, do you get this same result every time)?

**Comment by UdjinM6** [comment] 2018-06-11 19:24
This is an expected behaviour after https://github.com/dashpay/dash/pull/2097 is merged - outdated peers are skipped on sync, see https://github.com/dashpay/dash/blob/master/src/masternode-sync.cpp#L280 (and with spork10 ON and this PR merged outdated nodes are all nodes with proto < 70209).

**Closed** 2018-06-12 14:21 UTC
Labels: wontfix
