### ISSUE TITLE
InstantX should have "getixstatus {txid}" command

### ISSUE THREAD

**Issue by eduffield222** [dashpay/dash#660] opened 2015-12-18 23:53 UTC
After InstantX confirms on the network, it's hard to tell if it succeeded via the API. Currently the best way is to use gettransaction {txid}, then grab the "confirmations" which also includes IX confirmations . 

https://github.com/dashpay/dash/blob/master/src/rpcwallet.cpp#L1597

I propose adding a separate command, which would tell you if a transaction was safe. 
getixstatus {txid} -> returns "locked", "unknown", "unconfirmed" or "failure"

Also, adding the "ixstatus" field to gettransaction, which would make understanding the output a lot easier. 

Merchants running the full daemon could then easily utilize IX when receiving funds.

**Comment by PastaPastaPasta** [comment] 2018-09-17 03:35
Fixed by: https://github.com/dashpay/dash/pull/1628, should be closed @UdjinM6 @nmarley

**Comment by UdjinM6** [comment] 2018-09-17 11:43
Well, we never implemented anything like `getixstatus` but yes, all wallet tx-related RPCs should have `instantlock` (bool) field to indicate the IS status now. So the issue is half-fixed but I'm not sure if we need smth like `getixstatus` at all, probably not.

**Comment by PastaPastaPasta** [comment] 2018-09-17 12:40
Probably not, I don't think so.

**Comment by UdjinM6** [comment] 2019-01-27 21:39
All related rpc commands have `instantlock` field now which indicates whether tx was successfully locked or not. Closing.

**Closed by UdjinM6** 2019-01-27 21:39 UTC
Labels: enhancement
