### ISSUE TITLE
Make clean doesn't clean properly

### ISSUE THREAD

**Issue by Big-Brother** [dashpay/dash#2010] opened 2018-03-21 12:06 UTC
when you "make clean" in the main directory it leaves some files.. some over 200mb in size..

**Comment by nmarley** [comment] 2018-03-21 16:15
Can you list which files?

If you run `make distclean`, do the same files persist?

**Comment by nmarley** [comment] 2018-03-25 17:14
Closing, not a bug (this is usually expected without `make distclean`)

**Closed by nmarley** 2018-03-25 17:14 UTC
Labels: invalid
