### ISSUE TITLE
32-bit debugging wallets are not linking!

### ISSUE THREAD

**Issue by globaltoken** [dashpay/dash#2235] opened 2018-08-24 23:38 UTC
Hello,

I tried to build ARM & Linux 32 bit Wallets with debug enabled.
I noticed that they are not linking the daemon and the bench executable.

The error is attached in the .txt file.

Regards,
Pawel
[error.txt](https://github.com/dashpay/dash/files/2320175/error.txt)

**Comment by UdjinM6** [comment] 2018-08-24 23:49
Thanks for reporting! Which branch are you trying to build? Have you tried cleaning up and starting from scratch i.e. `make clean && ./autogen.sh && ./configure --whateveroptionsyouwereusing && make`?

**Comment by globaltoken** [comment] 2018-08-24 23:55
Hey!

Yes. 
I cloned it fresh from Github right now and tried it

**Comment by globaltoken** [comment] 2018-08-24 23:55
And I used the master branch

**Comment by UdjinM6** [comment] 2018-08-25 00:37
Hmmm.... I created a fresh new VM (Ubuntu 16.04, 32 bit) but I can't reproduce this neither for simple Linux 32 bit binaries nor for ARM cross-compiled ones. What are you machine specs (OS)? Are you following steps in https://github.com/dashpay/dash/blob/master/doc/build-unix.md? Have you used any other configure options besides `--enable-debug` (and those specified for ARM cross-compilation)?

**Comment by globaltoken** [comment] 2018-08-25 09:50
@UdjinM6 I build with Ubuntu 14.04 64bit, because my 16.04 is not able to build windows binaries.
I build it like discribed for 32 ARM:

cd ..
./configure --prefix=$PWD/depends/arm-linux-gnueabihf --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++ --enable-debug
make

Dont forget to enable debug, the normal wallets are linking fine.

Greetings,
Pawel

**Comment by UdjinM6** [comment] 2018-08-25 10:42
Spun up 14.04 and reproduced the issue. I guess the root here is that 14.04 uses fairly old gcc (4.8.4 on 14.04 in my case) and we use 16.04+ to compile.

This is easy to fix though:

```
diff --git a/src/masternodeman.cpp b/src/masternodeman.cpp
index bec58a4..407f610 100644
--- a/src/masternodeman.cpp
+++ b/src/masternodeman.cpp
@@ -26,6 +26,7 @@ CMasternodeMan mnodeman;
 
 const std::string CMasternodeMan::SERIALIZATION_VERSION_STRING = "CMasternodeMan-Version-8";
 const int CMasternodeMan::LAST_PAID_SCAN_BLOCKS = 100;
+const int CMasternodeMan::MAX_POSE_CONNECTIONS = 10;
 
 struct CompareLastPaidBlock
 {
diff --git a/src/masternodeman.h b/src/masternodeman.h
index cfceaed..d77fe11 100644
--- a/src/masternodeman.h
+++ b/src/masternodeman.h
@@ -29,7 +29,7 @@ private:
     static const int LAST_PAID_SCAN_BLOCKS;
 
     static const int MIN_POSE_PROTO_VERSION     = 70203;
-    static const int MAX_POSE_CONNECTIONS       = 10;
+    static const int MAX_POSE_CONNECTIONS;
     static const int MAX_POSE_RANK              = 10;
     static const int MAX_POSE_BLOCKS            = 10;
 
```
Apply this patch and this should do the work.

**Comment by UdjinM6** [comment] 2018-08-25 12:18
What's the error this time?

**Comment by globaltoken** [comment] 2018-08-25 14:13
Exactly the same error.

**Comment by UdjinM6** [comment] 2018-08-25 18:05
Weird. Are you sure you actually applied the patch to both (cpp/h) files?

**Comment by globaltoken** [comment] 2018-08-25 19:53
Yes, and the strange thing is that this just occurs on 32 bit Wallets.
The 64bit Wallets are okay

**Comment by UdjinM6** [comment] 2018-08-25 20:11
Hmmmm...
What gcc version are you using? (`gcc -v`)
Have you tried building from scratch after applying the patch? (`make clean` etc., not sure why would it made any difference but maybe there is some weirdness in linker/cacheing)
And just to clarify, so now the error says `/root/dash/src/masternodeman.cpp:1071` and not `/root/dash/src/masternodeman.cpp:1070`?

**Comment by globaltoken** [comment] 2018-08-28 05:57
@UdjinM6 I think it was a caching issue.
However, now it works!

Thanks for your help!

**Comment by UdjinM6** [comment] 2019-01-27 21:50
Issue was solved long time ago. Closing.

**Closed by UdjinM6** 2019-01-27 21:50 UTC
