### ISSUE TITLE
Linux 12.1 wallet won't allow outgoing transaction unless entire contents of wallet have 6 confirms

### ISSUE THREAD

**Issue by CryptoAmanda** [dashpay/dash#1034] opened 2016-09-20 00:38 UTC
I think the title sums it up. I have about 1000 tDash in my Linux 12.1 testnet wallet, and I was playing around with sending and receiving. When I tried to send 5 tDash to another wallet, it wouldn't let me unless every tDash in the entire wallet had 6 confirms -- even though hundreds and hundreds of them had 40+ confirms.

Here's the error I was getting. Hope I've submitted this report in a fashion even resembling normal.
![insufficient funds](https://cloud.githubusercontent.com/assets/13712662/18653589/23349e06-7e98-11e6-9981-152a5f45d177.png)

Additionally, I then enabled "coin control" so I could specifically select my inputs that had 40+ confirms, in case that made a difference. It did not. All tDash in the wallet had to have 6+ confirms for any outgoing transaction to be allowed.

**Comment by UdjinM6** [comment] 2016-09-20 12:07
I can't reproduce this :/ Which version are you running?

**Comment by CryptoAmanda** [comment] 2016-09-28 00:00
I was running dash-0.12.1-linux64.tar.gz

**Comment by CryptoAmanda** [comment] 2016-09-28 00:03
on Ubuntu, if that matters. I downloaded the wallet file from this link that Holger gave me: https://dashpay.atlassian.net/builds/browse/DASHL-DEV-641/artifact/JOB1/gitian-linux-dash-dist/

**Comment by nmarley** [comment] 2018-03-21 23:49
Hi Amanda,

Is this still an issue using the latest version of Dash-Qt?

**Comment by nmarley** [comment] 2019-03-30 20:04
I'll assume this is no longer an issue and close this. Please let us know if that's not the case! Thanks.

**Closed by nmarley** 2019-03-30 20:04 UTC
