### ISSUE TITLE
gui lag in version v12.2

### ISSUE THREAD

**Issue by demodun** [dashpay/dash#1702] opened 2017-10-28 23:55 UTC
Gui has been [reported to be laggy](https://www.dash.org/forum/threads/v12-2-testing.17412/page-2#post-143879) by a lot of people. The same happens in my system.
[Read here](https://github.com/dashpay/dash/pull/1699#issuecomment-340213709) my discovery, along with the explanation of an amateur and unprofessional solution I applied, in order to temporary solve the gui lag issue in my system, so that I could join the testnet.

**Comment by demodun** [comment] 2017-10-29 09:06
If I am about to name ONE responsible for the lag, I would say:
CMasternodeSync::ProcessTick

**Comment by codablock** [comment] 2017-10-31 09:28
https://github.com/dashpay/dash/pull/1704 should fix this

**Comment by demodun** [comment] 2017-10-31 14:38
>The lag bug also applies in 12.1, so if it is really a bug, please give me some bugcrowd tip.
@codablock  do you think that this issue applies in 12.1 also?
If yes, do you think that I deserve a bugcrowd tip?
And If yes, what tip would you give me if you were Jimbursch?

**Comment by UdjinM6** [comment] 2017-10-31 14:59
`cs_main` being a major reason of gui lag is a known issue. We and bitcoin devs are getting rid of it slowly in many parts of code and there is still a work to be done. It's not a bug in a usual sense, it's an implementation/design issue. Still have to be fixed of course.

**Comment by demodun** [comment] 2017-10-31 15:13
ok

**Comment by UdjinM6** [comment] 2017-11-01 15:55
should be fixed by #1704 , closing

**Closed by UdjinM6** 2017-11-01 15:55 UTC
