### ISSUE TITLE
Node stopped syncing while upgrading from v19.3.0 to v20.0.2 - Missing or invalid file /root/.dashcore/anchors.dat

### ISSUE THREAD

**Issue by UMANGAWASTHY** [dashpay/dash#5781] opened 2023-12-21 07:42 UTC
Hello Team
I am facing an issue while upgrading from v19.3.0 to v20.0.2.

Posix Signal: Segmentation fault,
No debug information available for stacktrace. You should add debug information and then run:,
dashd -printcrashinfo=bvcgc43iinzgc43ijfxgm3ybaacwiyltnbscaudponuxqictnftw4ylmhiqfgzlhnvsw45dboruw63ramzqxk3dubna4jdyaaaaaaagqh47hxjbjaaahq6tqaaaaaaaa44ftiaaaaaaaa7kbgqaaaaaaaawqwlyaaaaaaaadiokaaaaaaaacqtboaaaaaaaaycp6aaaaaaaaaraqin52ikiaacaaqs33uquqaaaa

Docker File - To build docker image

FROM debian:stable-slim

RUN apt-get update -y
RUN apt-get install -y curl
RUN curl -LOk https://github.com/dashpay/dash/releases/download/v20.0.2/dashcore-20.0.2-x86_64-linux-gnu.tar.gz
RUN tar --strip=2 -xzf *.tar.gz -C /usr/local/bin
WORKDIR /usr/local/bin
VOLUME ["/root/.dash"]
EXPOSE 9998 9999 19998 19999
ENTRYPOINT ["dashd"]

Docker compose File

version: '2'
services:
nodedash:
image: dash:v20.0.2
container_name: dashnode1332
restart: always
ports:
- "1332:9998"
- "127.0.0.1:9999:9999"
command: ["-disablewallet","-reindex","-rpcbind=dashnode1332","-rpcallowip=0.0.0.0/0","-printtoconsole=1","-onlynet=ipv4","-txindex","-dbcache=1024","-rpcthreads=128","-rpcuser=user","-rpcpassword=password","-blocksonly=1"]
volumes:
- /MyDisk/node-dash/data-3:/root/.dashcore
#mem_limit: 16g

Node logs
2023-12-21T07:34:03Z init message: Loading P2P addresses...
dashnode4332  | 2023-12-21T07:34:03Z Missing or invalid file /root/.dashcore/peers.dat
dashnode4332  | 2023-12-21T07:34:03Z Recreating peers.dat
dashnode4332  | 2023-12-21T07:34:03Z Missing or invalid file /root/.dashcore/anchors.dat
dashnode4332  | 2023-12-21T07:34:03Z 0 block-relay-only anchors will be tried for connections.
dashnode4332  | 2023-12-21T07:34:03Z init message: Starting network threads...
dashnode4332  | 2023-12-21T07:34:03Z net thread start
dashnode4332  | 2023-12-21T07:34:03Z dnsseed thread start
dashnode4332  | 2023-12-21T07:34:03Z Loading addresses from DNS seed dnsseed.dash.org
dashnode4332  | 2023-12-21T07:34:03Z addcon thread start
dashnode4332  | 2023-12-21T07:34:03Z opencon thread start
dashnode4332  | 2023-12-21T07:34:03Z mncon thread start
dashnode4332  | 2023-12-21T07:34:03Z init message: Done loading
dashnode4332  | 2023-12-21T07:34:03Z msghand thread start
dashnode4332  | 2023-12-21T07:34:03Z 25 addresses found from DNS seeds
dashnode4332  | 2023-12-21T07:34:03Z dnsseed thread exit
dashnode4332  | 2023-12-21T07:34:04Z New outbound peer connected: version: 70230, blocks=1991367, peer=0 (full-relay)
dashnode4332  | 2023-12-21T07:34:04Z Posix Signal: Segmentation fault
dashnode4332  | No debug information available for stacktrace. You should add debug information and then run:
dashnode4332  | dashd -printcrashinfo=bvcgc43iinzgc43ijfxgm3ybaacwiyltnbscaudponuxqictnftw4ylmhiqfgzlhnvsw45dboruw63ramzqxk3dubna4jdyaaaaaaagqf7hizybiaaahq6tqaaaaaaaa44ftiaaaaaaaa7kbgqaaaaaaaawqwlyaaaaaaaadiokaaaaaaaacqtboaaaaaaaaycp6aaaaaaaaaraa2ogoakaaacaprwum4auaaaaa
dashnode4332  | Posix Signal: Segmentation fault
dashnode4332  | No debug information available for stacktrace. You should add debug information and then run:
dashnode4332  | dashd -printcrashinfo=bvcgc43iinzgc43ijfxgm3ybaacwiyltnbscaudponuxqictnftw4ylmhiqfgzlhnvsw45dboruw63ramzqxk3dubna4jdyaaaaaaagqf7hizybiaaahq6tqaaaaaaaa44ftiaaaaaaaa7kbgqaaaaaaaawqwlyaaaaaaaadiokaaaaaaaacqtboaaaaaaaaycp6aaaaaaaaaraa2ogoakaaacaprwum4auaaaaa

Thanks
Umang Awasthy

**Comment by UMANGAWASTHY** [comment] 2024-01-02 09:00
@PastaPastaPasta

**Comment by PastaPastaPasta** [comment] 2024-01-02 16:44
closing as this is a duplicate of https://github.com/dashpay/dash/issues/5777

**Closed by PastaPastaPasta** 2024-01-02 16:44 UTC
