### ISSUE TITLE
[GUI] Send Tab PrivateSend/InstantSend Check Boxes to Dark

### ISSUE THREAD

**Issue by cassidysummers** [dashpay/dash#826] opened 2016-05-29 18:10 UTC
The privatesend and instantsend check boxes on the send tab are too dark. The contrast between the black background  and the green check mark is very bad. I would suggest changing the black background to some other color or changing the green check mark to white or a lighter color. 

![screenshot from 2016-05-29 11-08-32](https://cloud.githubusercontent.com/assets/5975813/15635230/e3507b56-258d-11e6-8a3b-8672d0ef2d58.png)
![screenshot from 2016-05-29 11-08-18](https://cloud.githubusercontent.com/assets/5975813/15635231/e7a8cdb6-258d-11e6-8406-23518fb3313d.png)

I've tested this on 4 different computer screens and they are all very hard to see.

**Comment by schinzelh** [comment] 2016-05-29 18:24
ping @crowning-

**Comment by crowning-** [comment] 2016-05-29 20:56
I'll have a look tomorrow, thanks for pinging :-)

**Comment by cassidysummers** [comment] 2016-05-30 02:18
I'm using Ubuntu 16.04 (is unity default? that's what I'm using). It looks alright on my laptop screen, still a little bit fuzzy though, and on my external monitor it's really hard to see. Maybe my eyes are just getting bad. What color green is that arrow?

**Comment by crowning-** [comment] 2016-05-30 05:52
If I remember correctly we don't set the the color, the color of the arrow+box depends on the desktop (not wallet!) theme you're using.
Should be an easy fix once I can reproduce the problem.

**Comment by crowning-** [comment] 2016-05-30 18:29
@schinzelh I installed an Ubuntu 16.04 testbox and found some things we need to address:

- Ubuntu 14.04 built binaries don't run on Ubuntu 16.04 because 14.04 uses boost 1.54, 16.06 uses boost 1.58. And the other way around is also a problem. This should be noted in the build-documentation. (I can do this)

- There are no 1.58 packages for Ubuntu 14.04, and no 1.54 packages for Ubuntu 16.06, so a 'normal' end-user won't be able to run dash-qt if the build was done on the 'other' system.

- The issue mentioned by @cassidysummers, even when not related to boost, disappears when you run a Ubuntu 16.04/boost 1.58  built wallet. 

I wouldn't want build version-dependent Linux binaries, but right now I don't see an easy way around this.
What do you think?

**Comment by schinzelh** [comment] 2016-05-30 18:47
@crowning- Hmm, did you test Bitcoin as well? Do they have the same issue?

**Comment by crowning-** [comment] 2016-05-30 19:51
Will try...

**Comment by crowning-** [comment] 2016-05-30 20:46
So, I built Bitcoin on Ubuntu 14.04 and 16.04 and it has the BOOST version issues as well.

Not the checkbox issues, though, but our traditional (sans-CSS) wallet doesn't has them either.

**Comment by crowning-** [comment] 2016-05-30 20:50
...on a second thought, our Gitian build runs on BOTH Ubuntus (minus the checkbox issue).

Do you know where the build scripts differ?

**Comment by schinzelh** [comment] 2016-05-30 20:58
Not sure what you mean with "runs on both"? You mean our gitian builds are compatible with Ubuntu 14.04 and 16.04, while the Bitcoin binaries from bitcoin.org/downloads do are not?

**Comment by crowning-** [comment] 2016-05-30 21:04
The Dash + Bitcoin Gitian builds run fine on both Ubuntus, but the Dash-build has the checkbox-issue in the non-Qt (aka CSS) themes on Ubuntu 16.04. I could fix the CSS-issue.

The Dash + Bitcoin native builds complain about the wrong BOOST version, but when given the correct BOOST dynamic (= *.so) library for each Ubuntu version they will run fine, and for the Dash-CSS-themes the checkboxes look okay.

**Comment by crowning-** [comment] 2016-06-01 08:20
Never mind, native builds are supposed to by dynamically build.

To be back on topic, I know the reason for the dark labels and will fix it later today or tomorrow.

**Comment by crowning-** [comment] 2016-06-02 06:35
**Status summary:**

1. there's no easy fix in CSS (that I know of) which works for all of our checkbox+background combinations AND looks good.
2. it's not clear whether Qt or Ubuntu 16.04 is the problem.
3. even if we should find some CSS-magic to solve this we could face the same problem again when the next update of OS (Ubuntu, Debian, SuSE, Redhat, etc.) times desktop (Gnome, Unity, KDE, etc.) times available desktop themes/color-schemes is available.
4. the behavior is different for native Dash builds and static builds via Gitian, so we would have to test both each time we test something. That's a serious PITA. I know because I did exactly this during the last days.

**My Conclusion:**

the simplest way to work around all those future problems would be to use our own images for checked/unchecked checkboxes. We did this already for the scrollbar-arrows (see https://github.com/dashpay/dash/tree/v0.12.1.x/src/qt/res/images/light), so we could do this easily for checkboxes as well, it's no big deal via CSS.

The only disadvantage I see is that we won't always have the latest blinky look of the underlying OS. OTOH this could also be and advantage :-)

At this point (and if nobody complains) I'd like to hand over to our trusted masters of beautiful image design @snogcel and @salmion .
If you should need help integrating/testing the new images into the Gitina build process we should coordinate this over at slack.

**Comment by schinzelh** [comment] 2016-06-02 06:53
@crowning- agree, there is no easy fix for this and it is an issue which we share with many multi OS software.

Having all images rendered out and not rely on underlying OS theme is ok for me.

**Comment by UdjinM6** [comment] 2016-06-08 16:06
@cassidysummers this should be fixed by #868, pls verify using test builds https://www.dash.org/forum/threads/v12-1-testnet-launch-thread.9014/page-18#post-96308
Thanks!

**Closed** 2016-12-08 21:42 UTC
Labels: bug
