### ISSUE TITLE
Build 0.13.0.0 fails on armv7l

### ISSUE THREAD

**Issue by PanderMusubi** [dashpay/dash#2562] opened 2018-12-17 17:16 UTC
I'm build on an armv7l system with Ubuntu 18.04 that could build 0.12.3.3 without problems.

Building 0.13.0.0-rc9 fails on:

   cd depends
   make

with

    Postprocessing native_protobuf...
    Caching native_protobuf...
    Fetching boost_1_63_0.tar.bz2 from https://sourceforge.net/projects/boost/files/boost/1.63.0
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100   357  100   357    0     0    401      0 --:--:-- --:--:-- --:--:--   400
    100   433  100   433    0     0    383      0  0:00:01  0:00:01 --:--:--   383
    100   347  100   347    0     0    180      0  0:00:01  0:00:01 --:--:--   966
    100 78.1M  100 78.1M    0     0   979k      0  0:01:21  0:01:21 --:--:--  550k
    /home/dash/dash-0.13.0.0-rc9/depends/work/download/boost-1_63_0/boost_1_63_0.tar.bz2.temp: OK
    Extracting boost...
    /home/dash/dash-0.13.0.0-rc9/depends/sources/boost_1_63_0.tar.bz2: OK
    Preprocessing boost...
    Configuring boost...
    Building Boost.Build engine with toolset gcc... tools/build/src/engine/bin.linuxarm/b2
    Unicode/ICU support for Boost.Regex?... disabled.
    Generating Boost.Build configuration in project-config.jam...
    
    Bootstrapping is done. To build, run:
    
        ./b2
        
    To adjust configuration, edit 'project-config.jam'.
    Further information:
    
       - Command line help:
         ./b2 --help
         
       - Getting started guide: 
         http://www.boost.org/more/getting_started/unix-variants.html
         
       - Boost.Build documentation:
         http://www.boost.org/build/doc/html/index.html
    
    Building boost...
    /home/dash/dash-0.13.0.0-rc9/depends/work/build/armv7l-unknown-linux-gnueabihf/boost/1_63_0-f2730e55940/tools/build/src/tools/gcc.jam:84: in gcc.init from module gcc
    error: toolset gcc initialization:
    error: provided command 'armv7l-unknown-linux-gnueabihf-g++' not found
    error: initialized from /home/dash/dash-0.13.0.0-rc9/depends/work/build/armv7l-unknown-linux-gnueabihf/boost/1_63_0-f2730e55940/user-config.jam:1
    /home/dash/dash-0.13.0.0-rc9/depends/work/build/armv7l-unknown-linux-gnueabihf/boost/1_63_0-f2730e55940/tools/build/src/build/toolset.jam:43: in toolset.using from module toolset
    /home/dash/dash-0.13.0.0-rc9/depends/work/build/armv7l-unknown-linux-gnueabihf/boost/1_63_0-f2730e55940/tools/build/src/build/project.jam:1052: in using from module project-rules
    /home/dash/dash-0.13.0.0-rc9/depends/work/build/armv7l-unknown-linux-gnueabihf/boost/1_63_0-f2730e55940/user-config.jam:1: in modules.load from module user-config
    /home/dash/dash-0.13.0.0-rc9/depends/work/build/armv7l-unknown-linux-gnueabihf/boost/1_63_0-f2730e55940/tools/build/src/build-system.jam:249: in load-config from module build-system
    /home/dash/dash-0.13.0.0-rc9/depends/work/build/armv7l-unknown-linux-gnueabihf/boost/1_63_0-f2730e55940/tools/build/src/build-system.jam:385: in load-configuration-files from module build-system
    /home/dash/dash-0.13.0.0-rc9/depends/work/build/armv7l-unknown-linux-gnueabihf/boost/1_63_0-f2730e55940/tools/build/src/build-system.jam:524: in load from module build-system
    /home/dash/dash-0.13.0.0-rc9/depends/work/build/armv7l-unknown-linux-gnueabihf/boost/1_63_0-f2730e55940/tools/build/src/kernel/modules.jam:295: in import from module modules
    /home/dash/dash-0.13.0.0-rc9/depends/work/build/armv7l-unknown-linux-gnueabihf/boost/1_63_0-f2730e55940/tools/build/src/kernel/bootstrap.jam:139: in boost-build from module
    /home/dash/dash-0.13.0.0-rc9/depends/work/build/armv7l-unknown-linux-gnueabihf/boost/1_63_0-f2730e55940/boost-build.jam:17: in module scope from module
    
    funcs.mk:242: recipe for target '/home/dash/dash-0.13.0.0-rc9/depends/work/build/armv7l-unknown-linux-gnueabihf/boost/1_63_0-f2730e55940/./.stamp_built' failed
    make: *** [/home/dash/dash-0.13.0.0-rc9/depends/work/build/armv7l-unknown-linux-gnueabihf/boost/1_63_0-f2730e55940/./.stamp_built] Error 1

**Comment by PastaPastaPasta** [comment] 2018-12-17 19:14
Are you building with the depends system as described https://github.com/dashpay/dash/blob/develop/doc/build-generic.md?

**Comment by PanderMusubi** [comment] 2018-12-17 22:03
Yes, and I have compiled also other wallets on this system. Since this `depends` part is new to the build, it didn't failed on me before.

It cannot find `armv7l-unknown-linux-gnueabihf-g++`. The system does have:

    /usr/bin/arm-linux-gnueabihf-g++ -> g++-7
    /usr/bin/arm-linux-gnueabihf-g++-7
    /usr/bin/g++ -> g++-7
    /usr/bin/g++-7 -> arm-linux-gnueabihf-g++-7

Perhaps a symbolic link is a quick fix, but I'm not familiar with this build step at all. And, better for a sustainable fix.

Slightly related issues (which are out of my depth to see what to apply to fix this) are:
* https://forum.odroid.com/viewtopic.php?f=96&t=8334&start=50
* https://www.raspberrypi.org/forums/viewtopic.php?t=105716
* https://forums.gentoo.org/viewtopic-p-7542294.html?sid=44abe3b4dc014378a33a1c790de99a28

**Comment by PanderMusubi** [comment] 2018-12-17 22:09
Is g++-7 the correct version? Is g++-multilib perhaps needed? Is it a bug in the Boost bootstrap?

**Comment by strophy** [comment] 2018-12-20 12:20
I can confirm this. Tested a self-build from the develop branch using the depends system under Ubuntu Mate native on Raspberry Pi 3 (armv7l) and got the same error.

**Comment by nmarley** [comment] 2018-12-20 12:30
Does anyone know how to test (e.g. reproduce) this w/o having physical access to a Raspberry Pi? I'd love to help provide a fix but harder to do w/o access to this build environment.

We might need to drop support for RISC machines like this as I'd imagine the actual need is small, but this is probably (maybe?) also a simple fix and I'd hate for enthusiasts to not be able to compile / run on RPi.

**Comment by PanderMusubi** [comment] 2018-12-20 12:44
I have Ubuntu 18.04 container in LXC on a Turris Omnia. That is where I did the build. I could give you access to it if you want. There are many people running wallets (also from other coins) on this hardware platform.

This might fail for all wallets using this. Perhaps find upstream maintainers that can fix building for this platform?

**Comment by PanderMusubi** [comment] 2018-12-20 13:09
Or you can give me (via e-mail) some pointers on what to try, such as e.g. creating a symbolic link for armv7l-unknown-linux-gnueabihf-g++

**Comment by thephez** [comment] 2018-12-20 13:36
@nmarley I've never tried it, but there are some sites that indicate you can run [Raspbian in qemu](https://www.unixmen.com/emulating-raspbian-using-qemu/). Might be an option for testing.

**Comment by PanderMusubi** [comment] 2018-12-20 16:37
I managed to build the depends for bitcoin-0.17.0.1.tar.gz successfully in Ubuntu 18.04 container on Turris Omnia using `make NO_QT=1`. So I dug in a little deeper. Results of `find . -name ''` are identical:

    depends# find . -name '*armv7l-unknown-linux-gnueabihf*'
    ./armv7l-unknown-linux-gnueabihf
    ./built/armv7l-unknown-linux-gnueabihf
    ./work/staging/armv7l-unknown-linux-gnueabihf
    ./work/build/armv7l-unknown-linux-gnueabihf

But with grep:

    dash-0.13.0.0-rc9/depends# grep -riI armv7l-unknown-linux-gnueabihf *              
    work/build/armv7l-unknown-linux-gnueabihf/boost/1_63_0-f2730e55940/user-config.jam:using gcc : : armv7l-unknown-linux-gnueabihf-g++ : <cxxflags>"-std=c++11 -fvisibility=hidden   -fPIC   -I/home/dash/dash-0.13.0.0-rc9/depends/armv7l-unknown-linux-gnueabihf/include    " <linkflags>"-L/home/dash/dash-0.13.0.0-rc9/depends/armv7l-unknown-linux-gnueabihf/lib    " <archiver>"armv7l-unknown-linux-gnueabihf-ar" <striper>"armv7l-unknown-linux-gnueabihf-strip"  <ranlib>"armv7l-unknown-linux-gnueabihf-ranlib" <rc>"" : ;

has only one result. But in bitcoin is has **11787** results. When excluding ^work, only 23 remain:

    bitcoin-0.17.0.1/depends# grep -riI armv7l-unknown-linux-gnueabihf *|grep -v ^work       
    armv7l-unknown-linux-gnueabihf/share/config.site:host_alias=armv7l-unknown-linux-gnueabihf
    armv7l-unknown-linux-gnueabihf/include/miniupnpc/miniupnpcstrings.h:#define OS_STRING "armv7l-unknown-linux-gnueabihf"
    armv7l-unknown-linux-gnueabihf/include/openssl/opensslconf.h:#define ENGINESDIR "/root/bitcoin-0.17.0.1/depends/armv7l-unknown-linux-gnueabihf/lib/engines"
    armv7l-unknown-linux-gnueabihf/include/openssl/opensslconf.h:#define OPENSSLDIR "/root/bitcoin-0.17.0.1/depends/armv7l-unknown-linux-gnueabihf/etc/openssl"
    armv7l-unknown-linux-gnueabihf/lib/libevent_extra.la:dependency_libs=' -L/root/bitcoin-0.17.0.1/depends/armv7l-unknown-linux-gnueabihf/lib'
    armv7l-unknown-linux-gnueabihf/lib/libevent_extra.la:libdir='/root/bitcoin-0.17.0.1/depends/armv7l-unknown-linux-gnueabihf/lib'
    armv7l-unknown-linux-gnueabihf/lib/libevent_pthreads.la:dependency_libs=' -L/root/bitcoin-0.17.0.1/depends/armv7l-unknown-linux-gnueabihf/lib'
    armv7l-unknown-linux-gnueabihf/lib/libevent_pthreads.la:libdir='/root/bitcoin-0.17.0.1/depends/armv7l-unknown-linux-gnueabihf/lib'
    armv7l-unknown-linux-gnueabihf/lib/libevent.la:dependency_libs=' -L/root/bitcoin-0.17.0.1/depends/armv7l-unknown-linux-gnueabihf/lib'
    armv7l-unknown-linux-gnueabihf/lib/libevent.la:libdir='/root/bitcoin-0.17.0.1/depends/armv7l-unknown-linux-gnueabihf/lib'
    armv7l-unknown-linux-gnueabihf/lib/libzmq.la:dependency_libs=' -L/root/bitcoin-0.17.0.1/depends/armv7l-unknown-linux-gnueabihf/lib -lrt -lpthread -ldl'
    armv7l-unknown-linux-gnueabihf/lib/libzmq.la:libdir='/root/bitcoin-0.17.0.1/depends/armv7l-unknown-linux-gnueabihf/lib'
    armv7l-unknown-linux-gnueabihf/lib/pkgconfig/libevent_core.pc:prefix=/root/bitcoin-0.17.0.1/depends/armv7l-unknown-linux-gnueabihf
    armv7l-unknown-linux-gnueabihf/lib/pkgconfig/libevent_extra.pc:prefix=/root/bitcoin-0.17.0.1/depends/armv7l-unknown-linux-gnueabihf
    armv7l-unknown-linux-gnueabihf/lib/pkgconfig/libcrypto.pc:prefix=/root/bitcoin-0.17.0.1/depends/armv7l-unknown-linux-gnueabihf
    armv7l-unknown-linux-gnueabihf/lib/pkgconfig/openssl.pc:prefix=/root/bitcoin-0.17.0.1/depends/armv7l-unknown-linux-gnueabihf
    armv7l-unknown-linux-gnueabihf/lib/pkgconfig/libssl.pc:prefix=/root/bitcoin-0.17.0.1/depends/armv7l-unknown-linux-gnueabihf
    armv7l-unknown-linux-gnueabihf/lib/pkgconfig/libzmq.pc.old:prefix=/root/bitcoin-0.17.0.1/depends/armv7l-unknown-linux-gnueabihf
    armv7l-unknown-linux-gnueabihf/lib/pkgconfig/libevent_pthreads.pc:prefix=/root/bitcoin-0.17.0.1/depends/armv7l-unknown-linux-gnueabihf
    armv7l-unknown-linux-gnueabihf/lib/pkgconfig/libevent.pc:prefix=/root/bitcoin-0.17.0.1/depends/armv7l-unknown-linux-gnueabihf
    armv7l-unknown-linux-gnueabihf/lib/pkgconfig/libzmq.pc:prefix=/root/bitcoin-0.17.0.1/depends/armv7l-unknown-linux-gnueabihf
    armv7l-unknown-linux-gnueabihf/lib/libevent_core.la:dependency_libs=' -L/root/bitcoin-0.17.0.1/depends/armv7l-unknown-linux-gnueabihf/lib'
    armv7l-unknown-linux-gnueabihf/lib/libevent_core.la:libdir='/root/bitcoin-0.17.0.1/depends/armv7l-unknown-linux-gnueabihf/lib'

Perhaps the line with `share/config.site:host_alias=` needs to be added to dash?

**Comment by PanderMusubi** [comment] 2018-12-20 20:15
I could replicate the same on a Raspberry Pi with Raspbian stretch.

**Comment by PanderMusubi** [comment] 2018-12-23 13:46
It is probably only a small configuration setting that needs to be fixed. Has https://github.com/dashpay/dash/releases/tag/v0.13.0.0-rc10 changes regarding this?

**Comment by PanderMusubi** [comment] 2018-12-23 15:55
Fails in the same way for rc10

**Comment by nmarley** [comment] 2018-12-23 18:52
Looks related: https://github.com/bitcoin/bitcoin/issues/6882

I've started a cross-compile on x86_64 (Ubuntu 18.04) and it seems to be building the dependencies w/o issue. I did have to install the `g++-arm-linux-gnueabihf ` package as suggested on Ubuntu, but it seems like that would be native on your system, so not sure how to help you there (you might try installing that?).

Have you instead tried [cross-compiling for ARM](https://github.com/dashpay/dash/blob/develop/doc/build-cross.md#arm-linux-cross-compilation) on a x64_32 system?

**Comment by nmarley** [comment] 2018-12-23 18:57
Update: apparently this cross-compiled the ARM binaries fine, but I have no way to test them. But we also offer these binaries via [our releases](https://github.com/dashpay/dash/releases).

Since cross-compiling and downloading pre-compiled ARM binaries is a possibility, I'm not sure it makes strategic sense to continue supporting compiling on ARM hardware.

@codablock @UdjinM6 Any thoughts, or would you agree/disagree?

**Comment by PanderMusubi** [comment] 2018-12-26 11:07
I did:

    sudo ln -s /usr/bin/arm-linux-gnueabihf-g++ /usr/bin/armv7l-unknown-linux-gnueabihf-g++
    sudo ln -s /usr/bin/arm-linux-gnueabihf-ar /usr/bin/armv7l-unknown-linux-gnueabihf-ar
    sudo ln -s /usr/bin/arm-linux-gnueabihf-ranlib /usr/bin/armv7l-unknown-linux-gnueabihf-ranlib

and than it fails at:

    /home/dash/dash-0.13.0.0-rc10/depends/work/download/openssl-1.0.1k/openssl-1.0.1k.tar.gz.temp: OK
    Extracting openssl...
    /home/dash/dash-0.13.0.0-rc10/depends/sources/openssl-1.0.1k.tar.gz: OK
    Preprocessing openssl...
    Configuring openssl...
    Configuring for 
    Usage: Configure [no-<cipher> ...] [enable-<cipher> ...] [experimental-<cipher> ...] [-Dxxx] [-lxxx] [-Lxxx] [-fxxx] [-Kxxx] [no-hw-xxx|no-hw] [[no-]threads] [[no-]shared] [[no-]zlib|zlib-dynamic] [no-asm] [no-dso] [no-krb5] [sctp] [386] [--prefix=DIR] [--openssldir=OPENSSLDIR] [--with-xxx[=vvv]] [--test-sanity] os/compiler[:flags]
    
    pick os/compiler from:
    BC-32 BS2000-OSD BSD-generic32 BSD-generic64 BSD-ia64 BSD-sparc64 BSD-sparcv8 
    BSD-x86 BSD-x86-elf BSD-x86_64 Cygwin Cygwin-pre1.3 DJGPP MPE/iX-gcc OS2-EMX 
    OS390-Unix QNX6 QNX6-i386 ReliantUNIX SINIX SINIX-N UWIN VC-CE VC-WIN32 
    VC-WIN64A VC-WIN64I aix-cc aix-gcc aix3-cc aix64-cc aix64-gcc android 
    android-armv7 android-x86 aux3-gcc beos-x86-bone beos-x86-r5 bsdi-elf-gcc cc 
    cray-j90 cray-t3e darwin-i386-cc darwin-ppc-cc darwin64-ppc-cc 
    darwin64-x86_64-cc dgux-R3-gcc dgux-R4-gcc dgux-R4-x86-gcc dist gcc hpux-cc 
    hpux-gcc hpux-ia64-cc hpux-ia64-gcc hpux-parisc-cc hpux-parisc-cc-o4 
    hpux-parisc-gcc hpux-parisc1_1-cc hpux-parisc1_1-gcc hpux-parisc2-cc 
    hpux-parisc2-gcc hpux64-ia64-cc hpux64-ia64-gcc hpux64-parisc2-cc 
    hpux64-parisc2-gcc hurd-x86 iphoneos-cross irix-cc irix-gcc irix-mips3-cc 
    irix-mips3-gcc irix64-mips4-cc irix64-mips4-gcc linux-alpha+bwx-ccc 
    linux-alpha+bwx-gcc linux-alpha-ccc linux-alpha-gcc linux-aout linux-armv4 
    linux-elf linux-generic32 linux-generic64 linux-ia32-icc linux-ia64 
    linux-ia64-ecc linux-ia64-icc linux-ppc linux-ppc64 linux-sparcv8 
    linux-sparcv9 linux-x86_64 linux32-s390x linux64-s390x linux64-sparcv9 mingw 
    mingw64 ncr-scde netware-clib netware-clib-bsdsock netware-clib-bsdsock-gcc 
    netware-clib-gcc netware-libc netware-libc-bsdsock netware-libc-bsdsock-gcc 
    netware-libc-gcc newsos4-gcc nextstep nextstep3.3 osf1-alpha-cc osf1-alpha-gcc 
    purify qnx4 rhapsody-ppc-cc sco5-cc sco5-gcc solaris-sparcv7-cc 
    solaris-sparcv7-gcc solaris-sparcv8-cc solaris-sparcv8-gcc solaris-sparcv9-cc 
    solaris-sparcv9-gcc solaris-x86-cc solaris-x86-gcc solaris64-sparcv9-cc 
    solaris64-sparcv9-gcc solaris64-x86_64-cc solaris64-x86_64-gcc sunos-gcc 
    tandem-c89 tru64-alpha-cc uClinux-dist uClinux-dist64 ultrix-cc ultrix-gcc 
    unixware-2.0 unixware-2.1 unixware-7 unixware-7-gcc vos-gcc vxworks-mips 
    vxworks-ppc405 vxworks-ppc60x vxworks-ppc750 vxworks-ppc750-debug 
    vxworks-ppc860 vxworks-ppcgen vxworks-simlinux debug debug-BSD-x86-elf 
    debug-Cygwin debug-VC-WIN32 debug-VC-WIN64A debug-VC-WIN64I debug-ben 
    debug-ben-darwin64 debug-ben-debug debug-ben-debug-64 debug-ben-macos 
    debug-ben-macos-gcc46 debug-ben-no-opt debug-ben-openbsd 
    debug-ben-openbsd-debug debug-ben-strict debug-bodo debug-darwin-i386-cc 
    debug-darwin-ppc-cc debug-geoff32 debug-geoff64 debug-levitte-linux-elf 
    debug-levitte-linux-elf-extreme debug-levitte-linux-noasm 
    debug-levitte-linux-noasm-extreme debug-linux-elf debug-linux-elf-noefence 
    debug-linux-generic32 debug-linux-generic64 debug-linux-ia32-aes 
    debug-linux-pentium debug-linux-ppro debug-linux-x86_64 debug-rse 
    debug-solaris-sparcv8-cc debug-solaris-sparcv8-gcc debug-solaris-sparcv9-cc 
    debug-solaris-sparcv9-gcc debug-steve-opt debug-steve32 debug-steve64 
    debug-ulf debug-vos-gcc 
    
    NOTE: If in doubt, on Unix-ish systems use './config'.
    funcs.mk:242: recipe for target '/home/dash/dash-0.13.0.0-rc10/depends/work/build/armv7l-unknown-linux-gnueabihf/openssl/1.0.1k-d3fa23462d0/./.stamp_configured' failed
    make: *** [/home/dash/dash-0.13.0.0-rc10/depends/work/build/armv7l-unknown-linux-gnueabihf/openssl/1.0.1k-d3fa23462d0/./.stamp_configured] Error 1

**Comment by PanderMusubi** [comment] 2018-12-26 11:10
There is `android-armv7` and `linux-armv4` but no `linux-armv7l` or similar combinations.

**Comment by strophy** [comment] 2018-12-27 05:52
Tried this under Arch Linux ARM on the advice of someone from Discord. In this distribution, the compiler works out of the box, but the linker again fails, causing building of boost to fail in a different way:
```
/bin/sh: line 1: armv7l-unknown-linux-gnueabihf-ar: command not found
/bin/sh: line 2: armv7l-unknown-linux-gnueabihf-ranlib: command not found
```
The following files exist:
```
/usr/bin/armv7l-unknown-linux-gnueabihf-c++
/usr/bin/armv7l-unknown-linux-gnueabihf-g++
/usr/bin/armv7l-unknown-linux-gnueabihf-gcc
/usr/bin/armv7l-unknown-linux-gnueabihf-gcc-8.2.0
/usr/bin/armv7l-unknown-linux-gnueabihf-gcc-ar
/usr/bin/armv7l-unknown-linux-gnueabihf-gcc-nm
/usr/bin/armv7l-unknown-linux-gnueabihf-gcc-ranlib
/usr/bin/armv7l-unknown-linux-gnueabihf-gcc-config
```

It seems [line 28 of boost.mk](https://github.com/dashpay/dash/blob/develop/depends/packages/boost.mk#L28) is specifying the host-platform triplet incorrectly in the user-config.jam file which b2 then uses to build boost. The variables filling the incorrect information are specified like `$($(package)_cxx)` or `$(host_RANLIB)` but I'm still learning about the makefile syntax that defines these variables, so this might take a while to figure out. I'll try and see how it is done in Bitcoin, but (like @nmarley said) nobody is building on ARM, so this is a pretty obscure problem.

**Comment by strophy** [comment] 2018-12-27 06:43
I think I [found the solution here](https://github.com/bitcoin/bitcoin/pull/12474) while checking how Bitcoin specifies the host platforms. I'm not sure why this works, but I'm testing it on my fork of Dash at the moment and will report back here if it builds successfully. Can anyone explain this syntax?

**Comment by strophy** [comment] 2018-12-28 11:14
Another update: I am now able to build Boost successfully. Building now fails on the gmp package with the following error:
```
 /usr/bin/gcc -std=gnu99 -c -DHAVE_CONFIG_H -I. -I.. -D__GMP_WITHIN_GMP -I.. -DOPERATION_divrem_1 -O2 -Wa,--noexecstack tmp-divrem_1.s -fPIC -DPIC -o .libs/divrem_1.o
tmp-divrem_1.s: Assembler messages:
tmp-divrem_1.s:129: Error: selected processor does not support ARM mode `mls r1,r4,r8,r11'
tmp-divrem_1.s:145: Error: selected processor does not support ARM mode `mls r1,r4,r8,r11'
tmp-divrem_1.s:158: Error: selected processor does not support ARM mode `mls r1,r4,r8,r11'
tmp-divrem_1.s:175: Error: selected processor does not support ARM mode `mls r1,r4,r3,r8'
tmp-divrem_1.s:209: Error: selected processor does not support ARM mode `mls r11,r4,r12,r3'

Makefile:768: recipe for target 'divrem_1.lo' failed
make[]: *** [divrem_1.lo] Error 1
```
gmp is a new package added in Dash 0.13 needed for BLS support. I tracked down the build error to a missing CFLAG that is causing the compiler to emit instructions the processor cannot understand. We need to add `-march=armv7-a` to `CFLAGS` and `CXXFLAGS` if building gmp under armv7l. It would probably be ok to add it for all packages building under armv7l if it is not possible to target just that package. Not quite sure how this should be done, but will keep digging tomorrow.

**Comment by PanderMusubi** [comment] 2018-12-28 11:16
That is nice progress. Let us know when we need to verify the workaround.

**Comment by strophy** [comment] 2018-12-29 08:13
I was able to resolve the gmp build errors by defining the CFLAGS as shown in [this commit](https://github.com/strophy/dash/commit/a53f6a1fcc2b832a2037dc861a2ae129e9be6e90). But I think I have now hit a fatal error building chia_bls:
```
[  2%] Building C object contrib/relic/src/CMakeFiles/relic_s.dir/relic_err.c.o
In file included from /home/strophy/dash/depends/work/build/armv7l-unknown-linux-gnueabihf/chia_bls/v20181101-dc66d29df29/contrib/relic/include/relic_arch.h:38:0,
                 from /home/strophy/dash/depends/work/build/armv7l-unknown-linux-gnueabihf/chia_bls/v20181101-dc66d29df29/contrib/relic/include/relic_util.h:38,
                 from /home/strophy/dash/depends/work/build/armv7l-unknown-linux-gnueabihf/chia_bls/v20181101-dc66d29df29/contrib/relic/include/relic_err.h:42,
                 from /home/strophy/dash/depends/work/build/armv7l-unknown-linux-gnueabihf/chia_bls/v20181101-dc66d29df29/contrib/relic/include/relic_core.h:43,
                 from /home/strophy/dash/depends/work/build/armv7l-unknown-linux-gnueabihf/chia_bls/v20181101-dc66d29df29/contrib/relic/src/relic_err.c:36:
/home/strophy/dash/depends/work/build/armv7l-unknown-linux-gnueabihf/chia_bls/v20181101-dc66d29df29/contrib/relic/include/relic_types.h:112:9: error: unknown type name ‘__uint128_t’
 typedef __uint128_t dbl_t;
         ^~~~~~~~~~~
contrib/relic/src/CMakeFiles/relic_s.dir/build.make:62: recipe for target 'contrib/relic/src/CMakeFiles/relic_s.dir/relic_err.c.o' failed
make[3]: *** [contrib/relic/src/CMakeFiles/relic_s.dir/relic_err.c.o] Error 1
make[3]: Leaving directory '/home/strophy/dash/depends/work/build/armv7l-unknown-linux-gnueabihf/chia_bls/v20181101-dc66d29df29/build'
CMakeFiles/Makefile2:136: recipe for target 'contrib/relic/src/CMakeFiles/relic_s.dir/all' failed
make[2]: *** [contrib/relic/src/CMakeFiles/relic_s.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
```
A bit of googling seems to show `__uint128_t` cannot be represented on a 32-bit architecture. A Raspberry Pi 3 is technically a Cortex-A53 implementing 64-bit ARMv8-A, but Raspbian is 32-bit to maintain compatibility with older Raspberry Pi models, so it reports armv7l, which is 32-bit. We could take this up with the Chia developers, but instead I might try and install a 64-bit OS on my Pi and see if I can get it working there. I believe Arch and Fedora may offer suitable distributions.

**Comment by PanderMusubi** [comment] 2018-12-29 16:34
In Bitcoin version 0.17.1, `__uint128_t` is not used. It uses `openssl-1.0.1k-e84cd35ad43` (where `grep -rI __uint128_t *` has no results), while dash version 0.13.0.0-rc10 uses `openssl/1.0.1k-d3fa23462d0` (`grep -rI __uint128_t *` has six results). So, there is a version of openssl that does not depend on this specific typedef.

**Comment by strophy** [comment] 2018-12-30 03:33
The problem is building [chia_bls](https://github.com/codablock/bls-signatures/releases/tag/v20181101), not openssl. Bitcoin does not use bls signatures and therefore does not depend on this library. If you can get this to build on armv7l, that would be a big step forward.

**Comment by PanderMusubi** [comment] 2018-12-30 17:44
Indeed doesn't build. Created an issue there in upstream repo. Could you inform https://github.com/codablock who made the fork for Dash?

**Comment by PanderMusubi** [comment] 2019-01-01 12:06
@strophy when 0.13 will be released, will people with master nodes on 0.12 be forced to upgrade?

**Comment by PanderMusubi** [comment] 2019-01-01 15:44
One way around is, is that Boost (which we are already using) can emulate`__uint128_t` see https://stackoverflow.com/questions/34588650/uint128-t-does-not-name-a-type Another suggestion is https://github.com/cisco/ChezScheme/issues/163#issuecomment-299412652

**Comment by codablock** [comment] 2019-01-02 06:08
Can you guys try this patch?
```
diff --git a/depends/packages/chia_bls.mk b/depends/packages/chia_bls.mk
index 85eb21472..2a54e0797 100644
--- a/depends/packages/chia_bls.mk
+++ b/depends/packages/chia_bls.mk
@@ -21,6 +21,7 @@ define $(package)_set_vars
   $(package)_config_opts_i686+= -DWSIZE=32
   $(package)_config_opts_x86_64+= -DWSIZE=64
   $(package)_config_opts_arm+= -DWSIZE=32
+  $(package)_config_opts_armv7l+= -DWSIZE=32
   $(package)_config_opts_debug=-DDEBUG=ON -DCMAKE_BUILD_TYPE=Debug
 
   ifneq ($(darwin_native_toolchain),)
```

**Comment by UdjinM6** [comment] 2019-01-03 12:34
@PanderMusubi make sure to add `--prefix=$(pwd)/depends/armv7l-unknown-linux-gnueabihf` option to configure command

**Comment by PanderMusubi** [comment] 2019-01-04 22:12
:+1::+1::+1:

It works and I could it test on both platforms with:

    make check
    cd src/test
    ./test_dash
    cd ..
    ./dashd -testnet &
    ./dash-cli getinfo # multiple times
    fg
    CTRL+C

**Comment by strophy** [comment] 2019-01-10 12:55
Was able to successfully build the develop branch of Dash on my Raspberry Pi 3 B (ARMv8-A) under Ubuntu 18.04 with host environment `aarch64-unknown-linux-gnu`  today as well. Both the natively built binaries and the RC11 release binaries sync on testnet with no problems. This issue can be closed.

**Comment by PanderMusubi** [comment] 2019-01-10 13:56
Super. So the change vorm armv7l has been incorporated into which RC? RC11?

**Comment by codablock** [comment] 2019-04-05 06:20
Closing as this seems to be resolved.

**Closed by codablock** 2019-04-05 06:20 UTC

**Comment by PanderMusubi** [comment] 2019-10-24 16:35
Small note, do not use `make -j` as it might consume too much resources (memory) and result in errors during compilation.
