### ISSUE TITLE
[Forwarded]: Masternode list-conf bug

### ISSUE THREAD

**Issue by globaltoken** [dashpay/dash#2309] opened 2018-09-20 11:44 UTC
Hello,

We at Globaltoken are using Masternodes as well, they were forked from current Dash Version.
Some user claimed a bug, that at Chaincoin also occured, they also forked your code.

Because we forked this Code from you, I think it is useful to let you know about known bugs.
More can be found here: https://github.com/chaincoin/chaincoin/commit/0db68a829b8f69e359532e8de199e8bb07e798ff

Cheers,
Pawel

**Comment by UdjinM6** [comment] 2018-09-20 12:15
Thanks for reporting but I can't reproduce the bug the patch is claiming to fix - `masternode list-conf` returns the full list of masternodes in masternode.conf for me. Yes, every object is a "masternode" and not some specific alias as in patched version but all the data is there.

**Comment by UdjinM6** [comment] 2018-09-20 12:29
I just checked that on testnet where I have multiple lines in masternode.conf for masternodes I don't own either. `list-conf` is a "dumb" one - it simply returns what it knows without checking anything, you just won't be able to start MNs if you don't control 1000 (t)DASH or to vote if you don't know the right mnprivkey.

**Comment by UdjinM6** [comment] 2019-03-06 11:08
Wasn't able to reproduce the issue and we are dropping masternode.conf anyway. Closing.

**Closed by UdjinM6** 2019-03-06 11:08 UTC
