### ISSUE TITLE
Abysmal Mixing liquidity on testnet.

### ISSUE THREAD

**Issue by PaulieD** [dashpay/dash#2094] opened 2018-06-03 21:54 UTC
Could one of you kind devs setup some nodes constantly mixing? I'd greatly appreciate it.

**Comment by nmarley** [comment] 2018-06-03 22:46
Hi, can I ask what is preventing you from doing the same thing? There's nothing special about being a developer that allows for mixing any differently than anyone else.

**Comment by PaulieD** [comment] 2018-06-03 23:15
@nmarley, you're right. I can and I am, but as you know, you need three in a mix. I might run a few vms to do it, but I can't do that forever and I'm sure others will want to test mixing and ps

**Comment by nmarley** [comment] 2018-06-04 05:04
That's a valid point -- but I'm not sure asking developers to do this via a Github issue is the appropriate way to get help w/the network. For one, the developers have plenty on their plates just maintaining the codebase. For another, maybe the Dash forum might be a better discussion forum for getting this assistance, and from the community at large, rather than just those interested in the code.

Wouldn't you agree that Github issues should generally be about the codebase itself, rather than network status at any given time? (Unless of course it's directly caused by some bug in the code, which I don't think is the case here.)

**Comment by PaulieD** [comment] 2018-06-04 12:35
Normally, I would agree with that. However, since this is the basis of being able to test key features in the new release, I find it to be pertinent that a normal environment is present and I think some of the best people to provide this would be those active on github.
In addition, I would like to see this become a regular service of dev-ops, that is, having nodes which are constantly online and mixing allowing users to properly use PrivateSend on testnet.
Thanks

**Comment by nmarley** [comment] 2018-06-05 00:07
> and I think some of the best people to provide this would be those active on github.

Maybe so, but that does not mean that they should be the ones to do so, or that it is strategic for developers to do so. The best use of developers' time and energy is development -- maintaining and improving the code base.

> In addition, I would like to see this become a regular service of dev-ops, that is, having nodes which are constantly online and mixing allowing users to properly use PrivateSend on testnet.

Perhaps, and internally our infrastructure team is following a devops methodology. But the developers are not, and this is not their responsibility. These are 2 separate groups, and the way to ask for support from the infrastructure/operations team is not thru a Github issue, as these should be focused on issues with the codebase.

We have a [support help desk](https://support.dash.org/support/home) which can be used to request this, as well as the 12.3 testing thread in the [Dash Forum](https://www.dash.org/forum)

Because this doesn't relate directly to the codebase and this isn't something developers should be doing themselves, I am going to close this issue as invalid, and ask that you request testnet mixing help thru one of the more pertinent channels that I've suggested. Thanks.

**Closed by nmarley** 2018-06-05 00:07 UTC
Labels: invalid
