### ISSUE TITLE
Master branch links to v0.11

### ISSUE THREAD

**Issue by Tharbad** [dashpay/dash#618] opened 2015-09-20 21:56 UTC
Can you fix it?

Thanks

**Comment by schinzelh** [comment] 2015-09-21 07:18
Not sure what you mean. If i checkout the git-repo I'll get the master branch which is at commit 22deeb7f9528c417cfecdd20bff513dd867de338 at the moment, which is latest release 0.12.0.53


```$ git clone https://github.com/dashpay/dash.git
Cloning into 'dash'...
remote: Counting objects: 73330, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 73330 (delta 0), reused 0 (delta 0), pack-reused 73326
Receiving objects: 100% (73330/73330), 84.27 MiB | 3.08 MiB/s, done.
Resolving deltas: 100% (52466/52466), done.
Checking connectivity... done.

Holger@SINJA /c/issue618
$ cd dash/

Holger@SINJA /c/issue618/dash (master)
$ git branch
* master

Holger@SINJA /c/issue618/dash (master)
$ git rev-parse HEAD
22deeb7f9528c417cfecdd20bff513dd867de338

Holger@SINJA /c/issue618/dash (master)
$```

**Comment by Tharbad** [comment] 2015-09-21 17:26
I've used 
git clone https://github.com/dashpay/dash.git
(Yesterday)

that's the head I got:
37e4d80920ce170c2564b96dd9c1678196cc6acb

My knowledge of git is not that good...

**Comment by elanaint** [comment] 2015-09-23 20:33
22deeb7f9528c417cfecdd20bff513dd867de338 here, fix your git copy.
https://github.com/dashpay/dash/commits/master

**Comment by schinzelh** [comment] 2015-09-28 16:21
Can't reproduce - closing.

**Closed by schinzelh** 2015-09-28 16:21 UTC
Labels: invalid, wontfix
