### ISSUE TITLE
GUI: Masternode tab doesn't refresh on MN status change

### ISSUE THREAD

**Issue by Technologov** [dashpay/dash#1420] opened 2017-03-29 00:11 UTC
Hello,

In Dash Core GUI, Masternode Tab, STATUS sub-tab, after some time my MNs are visible as 'NEW_START_REQUIRED', while from another wallet, my Masternodes shown up as 'ENABLED'.
Clearly one of the wallets are lying.

Restarting Dash Core doesn't solve the problem.

Version: Dash Core 12.1.4 on Windows 7 x64.

-Technologov, 29.03.2017.

**Comment by akijuh** [comment] 2017-03-29 13:57
https://github.com/dashpay/dash/issues/1338

**Comment by nmarley** [comment] 2018-04-27 00:45
Duplicate of #1338, closing

**Closed by nmarley** 2018-04-27 00:45 UTC
