### ISSUE TITLE
Missing / Unavailable Funds - TestNet Wallet

### ISSUE THREAD

**Issue by ryansd92** [dashpay/dash#1470] opened 2017-05-13 12:32 UTC
### Summary
I encountered some strange behavior on TestNet while generating a transaction history. I wrote a program to send Dash to an address outside my wallet every 3 seconds. In just a few minutes I was out of funds, but shouldn't have been.

### Set Up
I spun up two Ubuntu VPSs, each with their own wallet. I seeded one wallet with roughly 44,000 Dash spread over six separate transactions. On the other server, I left the wallet alone. The purpose of the second wallet was to receive funds from the first wallet.

On the VPS with the funded wallet, I wrote a Node.js program that would ask the second wallet over RPC for a deposit  address, then to randomly generate an amount of Dash to send between 1 Duff and 1/10th of a Dash (small amounts). Then, I would issue the `sendtoaddress` command over RPC to the locally funded wallet. Using a scheduler, the `sendtoaddress` command would be issued every 3 seconds.

### What Happened
The program ran fine for several blocks but then ran into `Insufficient funds`.

I was able to send 189 successful transactions over a six block period. The typical output of the program looked as follows:

```
RESULT=bc03847c9ac2dca1cf57189f6f4f399cad25b67b0174d3b6d84f630f0229effb
Amount=0.06143313

RESULT=3004d0b4c3b4b180e8f40db8dd9b6579ddfa1d72948a0323357f84306e127781
Amount=0.09618481

RESULT=01b868b9777dc3b0cde5bd4abcd19c314e2cc90c4b71cd87aabde27dcfef96b5
Amount=0.05452367
```

Very occasionally, I would get the following:

```
Amount=0.07025279
ERROR: Error: "500"{"result":null,"error":{"code":-4,"message":"Error: The transaction was rejected! This might happen if some of the coins in your wallet were already spent, such as if you used a copy of wallet.dat and coins were spent in the copy but not marked as spent here."},"id":1}
```

Finally, the program ran into the following, and would not ever find more available funds:

```
Amount=0.07471856
ERROR: Error: "500"{"result":null,"error":{"code":-6,"message":"Insufficient funds"},"id":1}
```

### Additional Information 
The six blocks containing all 189 transactions are in the following, in the formate `blockHeight - blockHash, - number-of-transactions`. You can see, they are consecutive blocks, which makes sense to me.

```
199633 - 0000000131cad42f54611ccefac391f0e8ed3fcf7ade1ad9db3a82e6a7624af0 - 45
199634 - 000000003943c757bc4242b31ffe22efb18cb5686bdd87c4d9ec7a81ae5579f3 - 6
199635 - 00000000c556e9f43d6d22f4bcead2aa4e8ad46dec91d1b2b39dad55c3558ad5 - 9
199636 - 0000000098ec20f4e6d87d9a031c57c1648637176cfa9c51c330cb1fedf9700f - 46
199637 - 00000001271ed1a0788dbd33a02f37ef407f03152b79f80b25472646dbfe9441 - 50
199638 - 0000000116faf698825a5958f64ad63d2ba4c2ab0dd0386e5daee3eabb1a9d8e - 33 
```

There is no way all 44K Dash was spent, not even close. So where did the Dash go? According to the blockchain, all my change addresses are quite well funded but when I ask my wallet, those addresses are empty. 

```
ubuntu@ip-10-0-0-25:~/TransactionCreator$ dash-cli getwalletinfo
{
  "walletversion": 61000,
  "balance": 0.00000000,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 0.00000000,
  "txcount": 201,
  "keypoololdest": 1494594921,
  "keypoolsize": 1001,
  "keys_left": 798,
  "paytxfee": 0.00000000
}
```

```
ubuntu@ip-10-0-0-25:~$ dash-cli getunconfirmedbalance
0.00000000
```

### Remaining Unconfirmed Transactions (After 23 Hours)

<img width="1040" alt="screen shot 2017-05-13 at 7 57 58 am" src="https://cloud.githubusercontent.com/assets/1169569/26025453/1bf267b8-37b6-11e7-81d9-13bb24a2539a.png">

### Original Funding Transactions
<img width="1030" alt="screen shot 2017-05-13 at 8 03 13 am" src="https://cloud.githubusercontent.com/assets/1169569/26025449/fae43862-37b5-11e7-807d-b73e000fdd68.png">

**Comment by ryansd92** [comment] 2017-05-15 11:50
### Update

Change addresses appear to have balances now, but with zero confirmations. When I filed the issue three days ago, the addresses showed as zero and when I clicked `inputs...` on the `Send` tab, there were no available inputs to select. Today, they are showing with the proper balances but with zero confirmations. The wallet is still searching for blocks because I just opened it so it's possible the confirmations will come in shortly. I will keep this ticket updated.

<img width="954" alt="screen shot 2017-05-15 at 7 43 55 am" src="https://cloud.githubusercontent.com/assets/1169569/26056216/5fef2202-3942-11e7-9e92-b8e380aa1557.png">

**Comment by tgflynn** [comment] 2017-05-15 14:39
@ryansd92 Thanks for this detailed report.

I'm curious how you came to investigate this. Have you seen something like this in normal operation ?

Also could you please specify which version of dash you were testing ?

**Comment by ryansd92** [comment] 2017-05-15 14:59
Yes, of course.  The version of Dash is `Dash Core RPC client version v0.12.1.5` I had downloaded the latest build as of three days ago. I am running this on Ubuntu 14.04.

I am working exclusively in TestNet so no, I have not experienced this in Mainnet.

I am working on a simulator for small frequent transactions that would mirror a real-life transactional sale system. To do this, I need a lot of test transactions. To create those test transactions, I wrote a program to generate 1 outbound transaction every three seconds. After a day, I would have a little less than 30,000 transactions.  I want to see how the network handles that. It's not really a lot of transactions and is a fraction of what Dash should be able to support.

I suspect what may be happening is that the wallet is using unconfirmed inputs that were change address from previous transactions within the same block. Though, I do not know enough about what happens under the hood in Dash to say this definitively. 

To test this, I am writing another program to take 10,000+ Dash from six addresses and send them to 10,000 outputs of 1 Dash each. Then, I should be able to generate at least 10,000 transactions of < 1 Dash each without choosing an unconfirmed input - so long as I use InstantSend to do it.

Perhaps my test is not realistic because in practice a user would probably not be buying a lot of items within 2.5 minutes without using InstantSend, which I believe requires the inputs to have 6 confirmations. In any case, I still have 44,000+ dash that have zero confirmations in my wallet.

This is very interesting to me and I would be happy to provide whatever you need from me to help figure this mystery out.

**Comment by ryansd92** [comment] 2017-05-15 15:04
To recreate this, all you need to two Dash installations within the same network. For convenience, I set the RPC username/password on both to the same thing so I could fetch addresses. You'll also need to open 19998 and allow RPC access internally, but I'm quite sure you know all that.

### Sample Transaction Generator
```
const rpc      = require('json-rpc2');
const schedule = require('node-schedule');

const RPC_USERNAME = 'foo';
const RPC_PASSWORD = 'bar';

const wallet    = rpc.Client.$create(19998, 'localhost', RPC_USERNAME, RPC_PASSWORD);
const merchant1 = rpc.Client.$create(19998, '10.0.0.132', RPC_USERNAME, RPC_PASSWORD);



newSendTransaction = function(address, amt, comment, commentTo, subtractfeefromamount, use_is, callback){
	wallet.call('sendtoaddress', [address, amt, comment, commentTo, subtractfeefromamount, use_is], function(err, result) {
	    if ( err ){
	    	callback(err);
	    }else{
	    	callback(null,result);
	    }
	});	
};

chooseAmount = function(callback){
	const ONE_DASH = 100000000;
	const ONE_TENTH_DASH = ONE_DASH / 10;
	const ONE_DUFF = 1;
	callback(null, (Math.floor(Math.random() * ONE_TENTH_DASH) + ONE_DUFF) / ONE_DASH);
};

fetchMerchantAddress = function(merchant, callback){
	merchant.call('getnewaddress', [], function(err, result){
		if ( err ){
			return callback(err);
		}else{
			// console.log('Result From Merchant=' + result);
			callback(null,result);
		}
	});
};


makeSale = function(){
	fetchMerchantAddress(merchant1, function(err_fetchMerchantAddress, payToAddress){
		if ( err_fetchMerchantAddress ){
			console.log('ERROR: ' + err_fetchMerchantAddress);
		}else{
			// console.log('PaymentAddress=' + payToAddress);
			chooseAmount(function(err_chooseAmount, amount){
				if ( err_chooseAmount ){
					console.log('ERROR: ' + err_chooseAmount);
				}else{
					console.log('Amount=' + amount)
					newSendTransaction(payToAddress, amount, 'stuff', 'Whole Foods', false, false, function(err_newSendTransaction, result){
						if ( err_newSendTransaction ){
							console.log('ERROR: ' + err_newSendTransaction);
						}else{
							console.log('RESULT=' + result);
						}
					});
				}
			});
		}
	});
};

var scheduledSales = schedule.scheduleJob('*/3 * * * * *', makeSale);


```

**Comment by ryansd92** [comment] 2017-05-15 19:01
@tgflynn I have an update. I sent 1 Dash to 2,000 addresses (https://test.explorer.dash.org/tx/ca9210e24e6582599cfa1dc8d4a5ac50d9ef72c9f585e4b4ddb47ad2815c25b7)

Then, I re-ran my script above but with InstantSend turned on. It's been running for a while now and has successfully sent around 1,000 < 1Dash transactions. This is good news. But, it still doesn't explain fully what's happening with standard, non-InstantSend transactions. I believe the Dash wallet is allowing transactions to be sent with unconfirmed inputs and that causes problems when miners decide to include/exclude a transaction from a block.

I am going to continue to the let the script run for a day and see what happens. If the wallet does indeed allow transaction to be formed with unconfirmed inputs, perhaps it should be changed to permit that behavior but not by default.

**Comment by tgflynn** [comment] 2017-05-15 19:11
In the GUI there is the option under Options->Wallet "Spend Unconfirmed Change".  But the RPC interface doesn't appear to let you control this.

The wallet should be able to keep up with new transactions even if unconfirmed inputs are used.  It sounds like it isn't doing that in this case and that must be a bug.

**Comment by ryansd92** [comment] 2017-05-15 19:15
Interesting. I see that in the GUI. I am using only the RPC commands so I bet you are right, this is likely a bug. Or, perhaps a poorly defaulted feature?

**Comment by craigbroadbear** [comment] 2018-03-29 02:12
I too am coming across "Error: The transaction was rejected! This might happen if some of the coins in your wallet were already spent, such as if you used a copy of wallet.dat and coins were spent in the copy but not marked as spent here."  

This is with dash core 0.12.2.3 on Windows.   

Using testnet.

My test sent 100 transactions using the RPC command 'sendtoaddress', one after the other with no delay between.   About 3 or 4 transactions would fail on each run with the above error.    My fix was to detect this error, pause for a second then retry.  That seemed to work.  

A lot of these transactions takes hours to be confirmed.  Is that to be expected?

**Comment by nmarley** [comment] 2018-03-29 02:19
Hmm... testnet is currently fragmented afaik, so this _might_ be affecting this. But I could be wrong.

Do you have information about the transactions, e.g. txids? I'm guessing it has to do with spending unconfirmed TXes.

Normally it shouldn't take hours for a TX to be confirmed on either mainnet or testnet, but I'm not sure how to debug "a lot of these transactions" without having more info to look into. Also, with 100 transactions, it's hard to cut thru the noise to find what's relevant.

Could you post more info and/or a debug.log (maybe using some pastebin type service) about the transactions which are taking hours to confirm? Or better yet, would you be able re-produce this with a smaller amount, say 5-10 transactions, and then post TXIDs / log info?

**Comment by codablock** [comment] 2018-03-29 02:43
This sounds like what some users were experiencing in https://www.dash.org/forum/threads/tech-issue-with-wallet-doing-1500-transactions-per-day.26172/#post-176803

Does a wallet restart help? If it's the same, the balance should be correct after a restart and transactions should start getting confirmed in the next blocks after the restart. Calling "resendwallettransactions" should also help instead of restarting.

**Comment by craigbroadbear** [comment] 2018-03-29 03:07
Wallet restart did the trick and the transactions are getting through now. 
If anyone wants to try it out, here is the little node test program I used:
```javascript
const unirest = require('unirest')

const config = {
    dashdUrl: "http://127.0.0.1:9998",
    dashUser: "xxx",
    dashPass: "xxxxxx"
}

function dashRPC(method, parms, cb)
{
    var payload = {
        jsonrpc: "1.0"
        , id: "dash-send-test.js"
        , method: method
        , params: parms
    };

    unirest.post(config.dashdUrl)
        .headers({"content-type": "text/plain"})
        .auth(config.dashUser, config.dashPass, true)
        .send( JSON.stringify(payload))
        .end(cb)

}

var add = "yfPq9XnLGGiGrtEGdm6RV5kaSwroXC63J4"

var sends = 0;
doSend()

function doSend() {
    if (sends++ >= 100)
        process.exit();

    dashRPC('sendtoaddress', [add, 0.001], (resp) => {
        console.log(JSON.stringify(resp.body, null, 2))
	if (resp.body.error)
		process.exit();
        doSend();
    })
}

```

**Comment by PastaPastaPasta** [comment] 2020-06-27 02:17
This seems to be resolved. To add a bit more detail, in order for a tx to be accepted to the mempool, it must not be a part of a long chain (25 txes) of unconfirmed txes. So what's happening is the wallet creates the tx, but it doesn't get added to the local mempool / broadcasted because it doesn't pass that rule. A wallet restart or running `resendwallettransactions` rpc command after some of the txes have confirmations will resolve the issue.

**Closed by PastaPastaPasta** 2020-06-27 02:17 UTC
