### ISSUE TITLE
std::thread issue

### ISSUE THREAD

**Issue by papicoin** [dashpay/dash#1751] opened 2017-12-02 06:26 UTC
Hello. When compiling for Windows on Linux make, i got this error:
`threadinterrupt.h:29:10: error: ‘condition_variable’ in namespace ‘std’ does not name a type
     std::condition_variable cond;
          ^
threadinterrupt.h:30:10: error: ‘mutex’ in namespace ‘std’ does not name a type
     std::mutex mut;
          ^
In file included from alert.cpp:10:0:
net.h:496:10: error: ‘condition_variable’ in namespace ‘std’ does not name a type
     std::condition_variable condMsgProc;
          ^
net.h:497:10: error: ‘mutex’ in namespace ‘std’ does not name a type
     std::mutex mutexMsgProc;
          ^
net.h:502:10: error: ‘thread’ in namespace ‘std’ does not name a type
     std::thread threadDNSAddressSeed;
          ^
net.h:503:10: error: ‘thread’ in namespace ‘std’ does not name a type
     std::thread threadSocketHandler;
          ^
net.h:504:10: error: ‘thread’ in namespace ‘std’ does not name a type
     std::thread threadOpenAddedConnections;
          ^
net.h:505:10: error: ‘thread’ in namespace ‘std’ does not name a type
     std::thread threadOpenConnections;
          ^
net.h:506:10: error: ‘thread’ in namespace ‘std’ does not name a type
     std::thread threadMnbRequestConnections;
          ^
net.h:507:10: error: ‘thread’ in namespace ‘std’ does not name a type
     std::thread threadMessageHandler;
`
How can I fix it?
P.S g++ -v is 5.4.0

**Comment by gladcow** [comment] 2017-12-02 19:22
Looks like incorrect compiler version without std thread support, or including wrong std headers. Look at this SO question, for example, - https://stackoverflow.com/questions/27939393/getting-error-mutex-in-namespace-std-does-not-name-a-type-in-mingw-mysys-pr#27939484

**Comment by z3ustb** [comment] 2017-12-27 09:17
I encountered the same problem and didn't fixed it by install the new version. Can anyone  give some more details on how to fix it?

**Comment by codablock** [comment] 2018-01-29 21:08
Had the same problem a few weeks ago. The problem is that mingw-w64 defaults to the "win32" implementation of the threading and synchronization classes. These do not provide all functionality yet. The solution is to switch to the "posix" implementation, which can be done with "update-alternatives" (on Debian/Ubuntu):
```bash
$ sudo update-alternatives --config i686-w64-mingw32-gcc
(select i686-w64-mingw32-gcc-posix)
$ sudo update-alternatives --config i686-w64-mingw32-g++
(select i686-w64-mingw32-g++-posix)
```

**Comment by nmarley** [comment] 2018-03-21 22:14
Closing as solution has been given ^

**Closed by nmarley** 2018-03-21 22:14 UTC
