### ISSUE TITLE
Signrawtransaction is not working on v17.0.0.0-rc3

### ISSUE THREAD

**Issue by gituser** [dashpay/dash#4080] opened 2021-04-01 14:58 UTC
### Describe the issue
If you try to use deprecated `signrawtransaction` it won't work on new version `v17.0.0.0-rc3`, but `signrawtransactionwithwallet` works.

#### If so, please list the steps to reproduce below:
1. Add another wallet to your dash instance with `./dash-cli createwallet test` 
2. Add `deprecatedrpc=signrawtransaction` into your dash.conf
3. Try to sign transaction with default wallet: 
4. Dash returns error:
```Wallet file not specified (must request wallet RPC through /wallet/<filename> uri-path).```

If you try to use new method `signrawtransactionwithwallet` it works just fine.

### Expected behaviour
`signrawtransaction` should work if there are multiple wallets and it's enabled via deprecated flag

### Actual behaviour
`signrawtransaction` fails

### What version of Dash Core are you using?
v17.0.0.0-rc3

### Machine specs:
- OS: Linux

**Comment by gituser** [comment] 2021-04-01 15:01
Ping @PastaPastaPasta @UdjinM6

**Comment by PastaPastaPasta** [comment] 2021-07-10 15:31
Thank you for reporting this. The issue is now fixed in develop, and will likely be released in a new minor release

**Closed by PastaPastaPasta** 2021-07-10 15:32 UTC
